version: "3.9"

services:
  web:
    build:
      context: .
      args:
        ENV_STATE: prod
    container_name: blogapi_web
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:17
    container_name: blogapi_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: blog
      POSTGRES_PASSWORD: blogapi87
      POSTGRES_DB: blogdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
